package pojo;
// Generated Jan 30, 2018 1:20:41 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Chapters generated by hbm2java
 */
@Entity
@Table(name="chapters"
    ,catalog="onlinexm"
)
public class Chapters  implements java.io.Serializable {


     private Integer chId;
     private Books books;
     private String chapterName;
     private Set questionerDefinations = new HashSet(0);
     private Set questionBanks = new HashSet(0);

    public Chapters() {
    }

    public Chapters(Books books, String chapterName, Set questionerDefinations, Set questionBanks) {
       this.books = books;
       this.chapterName = chapterName;
       this.questionerDefinations = questionerDefinations;
       this.questionBanks = questionBanks;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ch_id", unique=true, nullable=false)
    public Integer getChId() {
        return this.chId;
    }
    
    public void setChId(Integer chId) {
        this.chId = chId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="books_id")
    public Books getBooks() {
        return this.books;
    }
    
    public void setBooks(Books books) {
        this.books = books;
    }

    
    @Column(name="chapter_name", length=45)
    public String getChapterName() {
        return this.chapterName;
    }
    
    public void setChapterName(String chapterName) {
        this.chapterName = chapterName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="chapters")
    public Set getQuestionerDefinations() {
        return this.questionerDefinations;
    }
    
    public void setQuestionerDefinations(Set questionerDefinations) {
        this.questionerDefinations = questionerDefinations;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="chapters")
    public Set getQuestionBanks() {
        return this.questionBanks;
    }
    
    public void setQuestionBanks(Set questionBanks) {
        this.questionBanks = questionBanks;
    }




}


