package pojo;
// Generated Jan 30, 2018 1:20:41 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ExamShedular generated by hbm2java
 */
@Entity
@Table(name="exam_shedular"
    ,catalog="onlinexm"
)
public class ExamShedular  implements java.io.Serializable {


     private Integer esId;
     private Students students;
     private Date startTime;
     private Date end;
     private Date date;

    public ExamShedular() {
    }

    public ExamShedular(Students students, Date startTime, Date end, Date date) {
       this.students = students;
       this.startTime = startTime;
       this.end = end;
       this.date = date;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="es_id", unique=true, nullable=false)
    public Integer getEsId() {
        return this.esId;
    }
    
    public void setEsId(Integer esId) {
        this.esId = esId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="student_id")
    public Students getStudents() {
        return this.students;
    }
    
    public void setStudents(Students students) {
        this.students = students;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="start_time", length=8)
    public Date getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="end", length=8)
    public Date getEnd() {
        return this.end;
    }
    
    public void setEnd(Date end) {
        this.end = end;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date", length=10)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


