package pojo;
// Generated Jan 30, 2018 1:20:41 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Exam generated by hbm2java
 */
@Entity
@Table(name="exam"
    ,catalog="onlinexm"
)
public class Exam  implements java.io.Serializable {


     private Integer examId;
     private Courses courses;
     private String date;
     private Integer totalQus;
     private Date totalTime;
     private Set questionerDefinations = new HashSet(0);

    public Exam() {
    }

    public Exam(Courses courses, String date, Integer totalQus, Date totalTime, Set questionerDefinations) {
       this.courses = courses;
       this.date = date;
       this.totalQus = totalQus;
       this.totalTime = totalTime;
       this.questionerDefinations = questionerDefinations;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="exam_id", unique=true, nullable=false)
    public Integer getExamId() {
        return this.examId;
    }
    
    public void setExamId(Integer examId) {
        this.examId = examId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="course_id")
    public Courses getCourses() {
        return this.courses;
    }
    
    public void setCourses(Courses courses) {
        this.courses = courses;
    }

    
    @Column(name="date", length=45)
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }

    
    @Column(name="total_qus")
    public Integer getTotalQus() {
        return this.totalQus;
    }
    
    public void setTotalQus(Integer totalQus) {
        this.totalQus = totalQus;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="total_time", length=8)
    public Date getTotalTime() {
        return this.totalTime;
    }
    
    public void setTotalTime(Date totalTime) {
        this.totalTime = totalTime;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="exam")
    public Set getQuestionerDefinations() {
        return this.questionerDefinations;
    }
    
    public void setQuestionerDefinations(Set questionerDefinations) {
        this.questionerDefinations = questionerDefinations;
    }




}


