package pojo;
// Generated Jan 30, 2018 1:20:41 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * QuestionerDefination generated by hbm2java
 */
@Entity
@Table(name="questioner_defination"
    ,catalog="onlinexm"
)
public class QuestionerDefination  implements java.io.Serializable {


     private Integer definationId;
     private Books books;
     private Chapters chapters;
     private Courses courses;
     private Exam exam;
     private Reference reference;
     private Teachers teachers;
     private String qusLimitation;

    public QuestionerDefination() {
    }

    public QuestionerDefination(Books books, Chapters chapters, Courses courses, Exam exam, Reference reference, Teachers teachers, String qusLimitation) {
       this.books = books;
       this.chapters = chapters;
       this.courses = courses;
       this.exam = exam;
       this.reference = reference;
       this.teachers = teachers;
       this.qusLimitation = qusLimitation;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="defination_id", unique=true, nullable=false)
    public Integer getDefinationId() {
        return this.definationId;
    }
    
    public void setDefinationId(Integer definationId) {
        this.definationId = definationId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="book_id")
    public Books getBooks() {
        return this.books;
    }
    
    public void setBooks(Books books) {
        this.books = books;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ch_id")
    public Chapters getChapters() {
        return this.chapters;
    }
    
    public void setChapters(Chapters chapters) {
        this.chapters = chapters;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="course_id")
    public Courses getCourses() {
        return this.courses;
    }
    
    public void setCourses(Courses courses) {
        this.courses = courses;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="exam_id")
    public Exam getExam() {
        return this.exam;
    }
    
    public void setExam(Exam exam) {
        this.exam = exam;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ref_id")
    public Reference getReference() {
        return this.reference;
    }
    
    public void setReference(Reference reference) {
        this.reference = reference;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="teacher_id")
    public Teachers getTeachers() {
        return this.teachers;
    }
    
    public void setTeachers(Teachers teachers) {
        this.teachers = teachers;
    }

    
    @Column(name="qus_limitation", length=45)
    public String getQusLimitation() {
        return this.qusLimitation;
    }
    
    public void setQusLimitation(String qusLimitation) {
        this.qusLimitation = qusLimitation;
    }




}


