package pojo;
// Generated Jan 30, 2018 1:20:41 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * QuestionBank generated by hbm2java
 */
@Entity
@Table(name="question_bank"
    ,catalog="onlinexm"
)
public class QuestionBank  implements java.io.Serializable {


     private Integer qusBankId;
     private Books books;
     private Chapters chapters;
     private Courses courses;
     private Reference reference;
     private Teachers teachers;
     private String qusTitle;
     private String option1;
     private String option2;
     private String option3;
     private String option4;
     private Integer ans;
     private Set questionnaries = new HashSet(0);

    public QuestionBank() {
    }

    public QuestionBank(Books books, Chapters chapters, Courses courses, Reference reference, Teachers teachers, String qusTitle, String option1, String option2, String option3, String option4, Integer ans, Set questionnaries) {
       this.books = books;
       this.chapters = chapters;
       this.courses = courses;
       this.reference = reference;
       this.teachers = teachers;
       this.qusTitle = qusTitle;
       this.option1 = option1;
       this.option2 = option2;
       this.option3 = option3;
       this.option4 = option4;
       this.ans = ans;
       this.questionnaries = questionnaries;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="qus_bank_id", unique=true, nullable=false)
    public Integer getQusBankId() {
        return this.qusBankId;
    }
    
    public void setQusBankId(Integer qusBankId) {
        this.qusBankId = qusBankId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="books_id")
    public Books getBooks() {
        return this.books;
    }
    
    public void setBooks(Books books) {
        this.books = books;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ch_id")
    public Chapters getChapters() {
        return this.chapters;
    }
    
    public void setChapters(Chapters chapters) {
        this.chapters = chapters;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="course_id")
    public Courses getCourses() {
        return this.courses;
    }
    
    public void setCourses(Courses courses) {
        this.courses = courses;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ref_id")
    public Reference getReference() {
        return this.reference;
    }
    
    public void setReference(Reference reference) {
        this.reference = reference;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="teacher_id")
    public Teachers getTeachers() {
        return this.teachers;
    }
    
    public void setTeachers(Teachers teachers) {
        this.teachers = teachers;
    }

    
    @Column(name="qus_title", length=45)
    public String getQusTitle() {
        return this.qusTitle;
    }
    
    public void setQusTitle(String qusTitle) {
        this.qusTitle = qusTitle;
    }

    
    @Column(name="option1", length=45)
    public String getOption1() {
        return this.option1;
    }
    
    public void setOption1(String option1) {
        this.option1 = option1;
    }

    
    @Column(name="option2", length=45)
    public String getOption2() {
        return this.option2;
    }
    
    public void setOption2(String option2) {
        this.option2 = option2;
    }

    
    @Column(name="option3", length=45)
    public String getOption3() {
        return this.option3;
    }
    
    public void setOption3(String option3) {
        this.option3 = option3;
    }

    
    @Column(name="option4", length=45)
    public String getOption4() {
        return this.option4;
    }
    
    public void setOption4(String option4) {
        this.option4 = option4;
    }

    
    @Column(name="ans")
    public Integer getAns() {
        return this.ans;
    }
    
    public void setAns(Integer ans) {
        this.ans = ans;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="questionBank")
    public Set getQuestionnaries() {
        return this.questionnaries;
    }
    
    public void setQuestionnaries(Set questionnaries) {
        this.questionnaries = questionnaries;
    }




}


