package pojo;
// Generated Jan 30, 2018 1:20:41 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Questionnarie generated by hbm2java
 */
@Entity
@Table(name="questionnarie"
    ,catalog="onlinexm"
)
public class Questionnarie  implements java.io.Serializable {


     private Integer qusId;
     private QuestionBank questionBank;
     private Integer examId;
     private Integer studentId;
     private Integer collectedAns;

    public Questionnarie() {
    }

    public Questionnarie(QuestionBank questionBank, Integer examId, Integer studentId, Integer collectedAns) {
       this.questionBank = questionBank;
       this.examId = examId;
       this.studentId = studentId;
       this.collectedAns = collectedAns;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="qus_id", unique=true, nullable=false)
    public Integer getQusId() {
        return this.qusId;
    }
    
    public void setQusId(Integer qusId) {
        this.qusId = qusId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="qus_bank_id")
    public QuestionBank getQuestionBank() {
        return this.questionBank;
    }
    
    public void setQuestionBank(QuestionBank questionBank) {
        this.questionBank = questionBank;
    }

    
    @Column(name="exam_id")
    public Integer getExamId() {
        return this.examId;
    }
    
    public void setExamId(Integer examId) {
        this.examId = examId;
    }

    
    @Column(name="student_id")
    public Integer getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    
    @Column(name="collected_ans")
    public Integer getCollectedAns() {
        return this.collectedAns;
    }
    
    public void setCollectedAns(Integer collectedAns) {
        this.collectedAns = collectedAns;
    }




}


