package pojo;
// Generated Jan 30, 2018 1:20:41 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Reference generated by hbm2java
 */
@Entity
@Table(name="reference"
    ,catalog="onlinexm"
)
public class Reference  implements java.io.Serializable {


     private Integer refId;
     private Courses courses;
     private String reference;
     private Set questionerDefinations = new HashSet(0);
     private Set questionBanks = new HashSet(0);

    public Reference() {
    }

    public Reference(Courses courses, String reference, Set questionerDefinations, Set questionBanks) {
       this.courses = courses;
       this.reference = reference;
       this.questionerDefinations = questionerDefinations;
       this.questionBanks = questionBanks;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ref_id", unique=true, nullable=false)
    public Integer getRefId() {
        return this.refId;
    }
    
    public void setRefId(Integer refId) {
        this.refId = refId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="course_id")
    public Courses getCourses() {
        return this.courses;
    }
    
    public void setCourses(Courses courses) {
        this.courses = courses;
    }

    
    @Column(name="reference", length=45)
    public String getReference() {
        return this.reference;
    }
    
    public void setReference(String reference) {
        this.reference = reference;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="reference")
    public Set getQuestionerDefinations() {
        return this.questionerDefinations;
    }
    
    public void setQuestionerDefinations(Set questionerDefinations) {
        this.questionerDefinations = questionerDefinations;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="reference")
    public Set getQuestionBanks() {
        return this.questionBanks;
    }
    
    public void setQuestionBanks(Set questionBanks) {
        this.questionBanks = questionBanks;
    }




}


