package pojo;
// Generated Jan 30, 2018 1:20:41 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Students generated by hbm2java
 */
@Entity
@Table(name="students"
    ,catalog="onlinexm"
)
public class Students  implements java.io.Serializable {


     private Integer studentId;
     private Batchs batchs;
     private String selectedCourse;
     private Set examShedulars = new HashSet(0);

    public Students() {
    }

    public Students(Batchs batchs, String selectedCourse, Set examShedulars) {
       this.batchs = batchs;
       this.selectedCourse = selectedCourse;
       this.examShedulars = examShedulars;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="student_id", unique=true, nullable=false)
    public Integer getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="batch_id")
    public Batchs getBatchs() {
        return this.batchs;
    }
    
    public void setBatchs(Batchs batchs) {
        this.batchs = batchs;
    }

    
    @Column(name="selected_course", length=45)
    public String getSelectedCourse() {
        return this.selectedCourse;
    }
    
    public void setSelectedCourse(String selectedCourse) {
        this.selectedCourse = selectedCourse;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="students")
    public Set getExamShedulars() {
        return this.examShedulars;
    }
    
    public void setExamShedulars(Set examShedulars) {
        this.examShedulars = examShedulars;
    }




}


