package pojo;
// Generated Jan 30, 2018 1:20:41 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UsersRolea generated by hbm2java
 */
@Entity
@Table(name="users_rolea"
    ,catalog="onlinexm"
)
public class UsersRolea  implements java.io.Serializable {


     private UsersRoleaId id;
     private Roles roles;
     private Users users;

    public UsersRolea() {
    }

	
    public UsersRolea(UsersRoleaId id) {
        this.id = id;
    }
    public UsersRolea(UsersRoleaId id, Roles roles, Users users) {
       this.id = id;
       this.roles = roles;
       this.users = users;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="roleId", column=@Column(name="role_id") ), 
        @AttributeOverride(name="userId", column=@Column(name="user_id") ) } )
    public UsersRoleaId getId() {
        return this.id;
    }
    
    public void setId(UsersRoleaId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="role_id", insertable=false, updatable=false)
    public Roles getRoles() {
        return this.roles;
    }
    
    public void setRoles(Roles roles) {
        this.roles = roles;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", insertable=false, updatable=false)
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }




}


